- ignore: {name: Use camelCase}
- ignore: {name: "Reduce duplication", within: [FFI.*, Hardware.*, Main]}
- error: {lhs: error, rhs: SafetyResult, name: "Avoid error in safety critical code"}
- error: {lhs: undefined, rhs: SafetyResult, name: "Avoid undefined in safety critical code"}
