name: lambda-wave
version: 0.1.0.0

# Include the C code in the compilation
c-sources:
  - cbits/ring_buffer.c
include-dirs:
  - cbits

dependencies:
  - base >= 4.7 && < 5
  - stm                 # Software Transactional Memory
  - hmatrix             # Linear Algebra (requires LAPACK installed on OS)
  - binary              # Parsing
  - bytestring
  - clock               # High-res system timer
  - OpenGL
  - GLUT
  - vector              # High-perf arrays
  - serialport          # Cross-platform Serial

library:
  source-dirs: src

executables:
  lambda-wave-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded         # ENABLE MULTI-THREADING RUNTIME
    - -O2               # Aggressive Optimization
    - -with-rtsopts=-N  # Use all available CPU cores
    - -with-rtsopts=-A64m # Large allocation area to reduce GC frequency
    dependencies:
    - lambda-wave

tests:
  lambda-wave-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-wave
    - QuickCheck
    - hmatrix

benchmarks:
  lambda-wave-bench:
    main:                LatencyBench.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-wave
    - criterion
