#ifndef HARDWARE_MANIFEST_H
#define HARDWARE_MANIFEST_H

#include <termios.h>

#define MANIFEST_WATCHDOG_PIN 27
#define MANIFEST_LOGIC_PIN 17
#define MANIFEST_CONFIG_BAUD 115200
#define MANIFEST_CONFIG_BAUD_MACRO B115200
#define MANIFEST_DATA_BAUD 921600
#define MANIFEST_DATA_BAUD_MACRO B921600
#endif
